### ISSUE TITLE
Example of getting the ID of a zone

### ISSUE THREAD

**Issue by SoftCreatR** [robinbraemer/CloudflareAPI#11]
Thank you for building this API wrapper.

Would it be possible, that you could provide an example of how to obtain the ID for a specific zone? Because most zone related methods rely on the zone ID and i would prefer not to hardcode it.

What i've got so far (with my very little JAVA experience):

```JAVA
CloudflareResponse<List<Zone>> response =
    new CloudflareRequest(Category.LIST_ZONES, cfAccess)
        .queryString("name", "mydomain.tld")
        .asObjectList(Zone.class);
        
String jsonString = response.getJson().toString();
String zoneID = JsonPath.read(jsonString, "$.result[0].id");

System.out.print(zoneID);
```

That seems to work, but i'm curious, if there's an easier way. It would be nice, if we could utilize the methods within the object classes (e.g. `Zone.getId()`, etc.). Maybe, that's already possible and i'm just too stupid to figure it out 😆

**Comment by robinbraemer** [comment]
You can already do this.
Get the object such as the Zone via .getObject() and then .getId().

The Lombok Getter annotations (https://github.com/robinbraemer/CloudflareAPI/blob/2342e8d6ceaf5ada20e534385b393c914b018272/src/main/java/eu/roboflax/cloudflare/CloudflareResponse.java#L34) automatically generate getters for the object and response class.
