### ISSUE TITLE
No support for API Tokens

### ISSUE THREAD

**Issue by FlorentMasson** [robinbraemer/CloudflareAPI#14]
Would it be possible to have support for API tokens (`Authorization: Bearer <token>`) in addition to API keys?
https://api.cloudflare.com/#getting-started-requests
Thanks

**Comment by robinbraemer** [comment]
Sure, would you make a pull request adding token auth support?
Maybe you can introduce a new `AuthMethod` interface that applies its credentials to every API request and make a `TokenAuth` and `KeysAuth` class that implements `AuthMethod`, so users can choose from?

(Sorry for the late answer.)

**Comment by FlorentMasson** [comment]
Sorry, I selected another library which has it already
